### ISSUE TITLE
Code of Spatial Feature Alignment Network

### ISSUE THREAD

**Issue by SunHui1216** [VDT-2048/DVTOD#1]
Thank you for this wonderful work.
I have a question about the code. I couldn't find where the Spatial Feature Alignment Network in the paper was implemented in the code. If it's convenient, please guide me. Thank you!

**Comment by ironmanfcf** [comment]
我也有这个问题，请问你找到相关的代码了吗？

**Comment by SunHui1216** [comment]
没有的

**Comment by jacxue** [comment]
> Thank you for this wonderful work. I have a question about the code. I couldn't find where the Spatial Feature Alignment Network in the paper was implemented in the code. If it's convenient, please guide me. Thank you!

这个对齐网络是common.py中的MAM2这个类，返回的是fuse特征；
另外说一下查看网络各部分代码的方法：网络结构在models/my/yolov5s_fusion_dvtod.yaml中，按照配置文件去common.py里面去找就可以了

**Comment by jacxue** [comment]
> 我也有这个问题，请问你找到相关的代码了吗？
这个对齐网络是common.py中的MAM2这个类，返回的是fuse特征；

**Comment by SunHui1216** [comment]
> > Thank you for this wonderful work. I have a question about the code. I couldn't find where the Spatial Feature Alignment Network in the paper was implemented in the code. If it's convenient, please guide me. Thank you!
> 
> 这个对齐网络是common.py中的MAM2这个类，返回的是fuse特征； 另外说一下查看网络各部分代码的方法：网络结构在models/my/yolov5s_fusion_dvtod.yaml中，按照配置文件去common.py里面去找就可以了

谢谢！
